services:
  dani-boy-app:
    build:
      context: .
    restart: unless-stopped
    environment:
      PORT: "8001"
    volumes:
      - /srv/dani-boy/env/app.env:/app/.env:ro
    expose:
      - "8001"
    networks:
      prodoc_net:
        aliases:
          - dani-boy
          - dani-boy-app

networks:
  prodoc_net:
    external: true
    name: unesco-ed37_prodoc_net
